[package]
name = "codesage-core"
version = "0.1.0"
edition = "2021"
authors = ["CodeSage Contributors"]
license = "MIT"
description = "Core types and traits for CodeSage"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
